Enable additional configure options

diff --git a/configure_opencv b/configure_opencv
--- a/configure_opencv
+++ b/configure_opencv
@@ -3,7 +3,8 @@ if [ "$1" = "--help" -o "$1" = "-h" ]; then
 	echo "Usage: $0 [Options] [Enviroment Variables]"
 	echo ""
 	echo "OPTIONS"
-	echo "  -h, --help    Show this guide"
+	echo "  -h, --help           Show this guide"
+	echo "  -c, --configure-help Show configure help"
 	echo ""
 	echo "ENVIROMENT VARIABLES"
 	echo "  SDK_VERION    Select iPhone SDK Version (2.0, 2.1, 2.2, 2.2.1, 3.0, 3.1, 3.1.2 and more)"
@@ -12,6 +13,8 @@ if [ "$1" = "--help" -o "$1" = "-h" ]; then
 	echo "                Default = 4.0 for SDK 2.x, 4.2 for SDK 3.x"
 	echo "  ARCH          Select target architecture (device or simulator)"
 	echo "                Default = simulator"
+	echo "  CONFIGURE     Path to configure script"
+	echo "                Default = ../configure"
 	echo ""
 	echo "EXAMPLES"
 	echo "  % $0                             Making OpenCV with SDK3.1.2 using GCC4.2 for iPhone simulator"
@@ -20,6 +23,18 @@ if [ "$1" = "--help" -o "$1" = "-h" ]; then
 	echo "  % $0 SDK_VERSION=2.2.1           Making OpenCV with SDK2.2.1 using GCC4.0 for iPhone simulator"
 	exit
 fi
+if [ -z "${CONFIGURE}" ]; then
+	CONFIGURE=../configure
+fi
+if [ ! -e "${CONFIGURE}" ]; then
+	echo "Missing '${CONFIGURE}', please set the path to configure by CONFIGURE enviroment variable."
+	exit 1
+fi
+if [ "$1" = "--configure-help" -o "$1" = "-c" ]; then
+	${CONFIGURE} --help
+	exit
+fi
+
 if [ -z "${SDK_VERSION}" ]; then
 	SDK_VERSION=3.1.2
 fi
@@ -54,7 +69,8 @@ SDK=${PLATFORM}/Developer/SDKs/iPhone${ARCH_SDKNAME}${SDK_VERSION}.sdk
 PREFIX=`pwd`/`dirname $0`/opencv_${ARCH}
 PATH=/bin:/sbin:/usr/bin:/usr/sbin:${BIN}
 
-../configure --prefix=${PREFIX} \
+${CONFIGURE} \
+	--prefix=${PREFIX} \
 	--build=i686-apple-darwin9 \
 	--host=${ARCH_HOST}-apple-darwin9 \
 	--enable-static \
@@ -70,6 +86,7 @@ PATH=/bin:/sbin:/usr/bin:/usr/sbin:${BIN}
 	--without-carbon \
 	--without-gtk \
 	--without-gthread \
+	$* \
 	CC=${BIN}/gcc-${GCC_VERSION} \
 	CXX=${BIN}/g++-${GCC_VERSION} \
 	CFLAGS="-arch ${ARCH_FLAG} -isysroot ${SDK}" \
